# ===================================================================
#  Rucio Client Deployment
# ===================================================================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rucio-client
spec:
  replicas: {{ .Values.client.replicas }}
  selector:
    matchLabels:
      app: rucio-client
  template:
    metadata:
      labels:
        app: rucio-client
    spec:
      volumes:
      # This volume mounts the /etc/grid-security directory from the host node,
      # assuming your user certificates and CA's are present there.
      - name: grid-certificates
        hostPath:
          path: /etc/grid-security
      # This allows for additional volumes to be defined in values.yaml, same as the server.
      {{- with .Values.client.extraVolumes }}
      {{- toYaml . | nindent 8 }}
      {{- end }}

      containers:
      - name: rucio-client
        image: {{ .Values.client.image }}
        # This command keeps the pod running so you can connect to it.
        command: ["tail", "-f", "/dev/null"]
        volumeMounts:
          - name: grid-certificates
            mountPath: /etc/grid-security
            readOnly: true
        # This allows for additional volume mounts to be defined in values.yaml.
        {{- with .Values.client.extraVolumeMounts }}
        {{- toYaml . | nindent 12 }}
        {{- end }}
        env:
          # --- Rucio client configuration ---
          - name: RUCIO_HOST
            value: "{{ .Values.rucio.server.host }}"
          - name: RUCIO_AUTH_TYPE
            value: "x509"
          - name: RUCIO_ACCOUNT
            value: "{{ .Values.client.account }}"

          # --- X.509 certificate configuration ---
          # These paths should point to your client certificate and key
          # within the mounted /etc/grid-security volume.
          - name: X509_USER_CERT
            value: "{{ .Values.client.x509_cert }}"
          - name: X509_USER_KEY
            value: "{{ .Values.client.x509_key }}"
          - name: X509_CERT_DIR
            value: "/etc/grid-security/certificates"