{{- if .Values.initJob.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  # The name includes the Helm release name to be unique
  name: {{ .Release.Name }}-rucio-init-job
  labels:
    app: rucio-init-job
spec:
  template:
    metadata:
      labels:
        app: rucio-init-job
    spec:
      restartPolicy: Never
      containers:
        - name: init
          image: rucio/rucio-init:latest
          imagePullPolicy: Always
          env:
            - name: RUCIO_CFG_DATABASE_DEFAULT
              value: "postgresql+psycopg://{{ .Values.postgresql.auth.username }}:{{ .Values.postgresql.auth.password }}@{{ .Values.rucio.server.db_host }}:5432/{{ .Values.postgresql.auth.database }}"
            - name: RUCIO_CFG_BOOTSTRAP_USERPASS_IDENTITY
              value: "rucio"
            - name: RUCIO_CFG_BOOTSTRAP_USERPASS_PWD
              value: "rucio"
            - name: RUCIO_PRINT_CFG
              value: "true"
  backoffLimit: 4
{{- end }}