{{- if .Values.initJob.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-rucio-init-job
  labels:
    app: rucio-init-job
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
spec:
  template:
    spec:
      restartPolicy: OnFailure
      
      initContainers:
        - name: wait-for-db
          image: postgres:14
          imagePullPolicy: IfNotPresent
          env:
            - name: PGPASSWORD
              value: "{{ .Values.postgresql.auth.password }}"
          command: ['sh', '-c']
          args:
            - |
              set -ex
              echo "Waiting for database to be ready..."
              until pg_isready -h "{{ .Values.rucio.server.db_host }}" -p 5432 -U "{{ .Values.postgresql.auth.username }}" -d "{{ .Values.postgresql.auth.database }}"; do
                echo "Database is not ready yet. Retrying in 5 seconds..."
                sleep 5
              done
              echo "✅ Database is ready."

      containers:
        - name: db-init
          image: "{{ .Values.initJob.image }}"
          imagePullPolicy: Always
          env:
            - name: RUCIO_CFG_DATABASE_DEFAULT
              value: "postgresql+psycopg://{{ .Values.postgresql.auth.username }}:{{ .Values.postgresql.auth.password }}@{{ .Values.rucio.server.db_host }}/{{ .Values.postgresql.auth.database }}"
            - name: RUCIO_CFG_BOOTSTRAP_ACCOUNT
              value: "root"
            - name: RUCIO_CFG_BOOTSTRAP_X509_IDENTITY
              value: "{{ required "rucio.server.root_identity_dn is required in values.yaml!" .Values.rucio.server.root_identity_dn }}"
            - name: RUCIO_CFG_BOOTSTRAP_X509_EMAIL
              value: "rucio-root@example.com"
            - name: RUCIO_PRINT_CFG
              value: "true"
          # This command sequence first initializes the database, then adds the new identity.
          command: ['sh', '-c']
          args:
            - |
              set -ex
              # 1. Run the default entrypoint to create schema and root X.509 identity
              echo "Running default DB schema initialization..."
              /usr/local/bin/docker-entrypoint.sh

              # 2. Add the USERPASS identity to the same account
              echo "Adding USERPASS identity to account '{{ .Values.client.config.account }}'..."
              rucio-admin identity add --account {{ .Values.client.config.account }} \
                --type USERPASS \
                --username {{ .Values.client.config.username }} \
                --password {{ .Values.client.config.password }} \
                --email {{ .Values.client.config.username }}@example.com
              echo "✅ USERPASS identity created successfully."
{{- end }}