{{- if .Values.initJob.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-rucio-db-init-job
  labels:
    app: rucio-db-init-job
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      labels:
        app: rucio-db-init-job
    spec:
      restartPolicy: OnFailure
      
      initContainers:
        - name: wait-for-db
          image: busybox:1.36
          imagePullPolicy: IfNotPresent
          command: ['sh', '-c']
          args:
            - |
              set -ex
              DB_HOST="{{ .Values.rucio.server.db_host }}"
              # The port check requires an explicit port number.
              DB_PORT="5432"
              
              echo "Waiting for database at ${DB_HOST}:${DB_PORT}..."
              until nc -z -w 5 "${DB_HOST}" "${DB_PORT}"; do
                echo "Database is not ready yet. Retrying in 5 seconds..."
                sleep 5
              done
              echo "Database is ready."

      containers:
        - name: db-init
          image: rucio/rucio-init:latest
          imagePullPolicy: Always
          env:
            - name: RUCIO_CFG_DATABASE_DEFAULT
              value: "postgresql+psycopg://{{ .Values.postgresql.auth.username }}:{{ .Values.postgresql.auth.password }}@{{ .Values.rucio.server.db_host }}/{{ .Values.postgresql.auth.database }}"
            - name: RUCIO_CFG_BOOTSTRAP_USERPASS_IDENTITY
              value: "rucio"
            - name: RUCIO_CFG_BOOTSTRAP_USERPASS_PWD
              value: "rucio"
            - name: RUCIO_PRINT_CFG
              value: "true"
  backoffLimit: 4
{{- end }}