apiVersion: v1
kind: Secret
metadata:
  name: rucio-secrets
type: Opaque
data:
  db-password: {{ .Values.rucio.server.db_password | b64enc }}

---
# Secret for the Rucio Server's host certificate and key ONLY
apiVersion: v1
kind: Secret
metadata:
  name: rucio-server-certs
type: Opaque
data:
  hostcert.pem: {{ (.Files.Get "certificates/hostcert.pem") | b64enc }}
  hostkey.pem: {{ (.Files.Get "certificates/hostkey.pem") | b64enc }}

---
# Secret for the Rucio Client's x509 certificate and key ONLY
apiVersion: v1
kind: Secret
metadata:
  name: rucio-client-x509-secret
type: Opaque
data:
  usercert.pem: {{ (.Files.Get "certificates/usercert.pem") | b64enc }}
  userkey.pem: {{ (.Files.Get "certificates/userkey.pem") | b64enc }}

---
# OPTIONAL: If you want Helm to manage the CA secret automatically
# Secret for the CA certificate and its hash link
apiVersion: v1
kind: Secret
metadata:
  name: rucio-ca-secret
type: Opaque
data:
  ca.pem: {{ (.Files.Get "certificates/ca.pem") | b64enc }}
  209843b3.0: {{ (.Files.Get "certificates/209843b3.0") | b64enc }}

---
#  Secret for XRootD RSE
{{- if .Values.rseCredentials.boulbyXrootd.token }}
apiVersion: v1
kind: Secret
metadata:
  name: rucio-rse-boulby-xrootd-credentials
type: Opaque
data:
  # This creates a file named 'xrootd_token' in the secret
  xrootd_token: {{ .Values.rseCredentials.boulbyXrootd.token | b64enc }}
{{- end }}


---
# ===================================================================
#  Secret for Rucio Server OIDC Client Credentials
# ===================================================================
{{- if .Values.oidcCredentials.clientSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: rucio-oidc-secret
type: Opaque
data:
  # These will be the filenames inside the mounted volume
  oidc_client_id: {{ .Values.oidcCredentials.clientId | b64enc }}
  oidc_client_secret: {{ .Values.oidcCredentials.clientSecret | b64enc }}
{{- end }}