apiVersion: v1
kind: Secret
metadata:
  name: rucio-secrets
type: Opaque
data:
  db-password: {{ .Values.rucio.server.db_password | b64enc }}

---
apiVersion: v1
kind: Secret
metadata:
  name: rucio-server-certs
type: Opaque
data:
  hostcert.pem: {{ (.Files.Get "certificates/hostcert.pem") | b64enc }}
  hostkey.pem: {{ (.Files.Get "certificates/hostkey.pem") | b64enc }}

---
apiVersion: v1
kind: Secret
metadata:
  name: rucio-client-x509-secret
type: Opaque
data:
  usercert.pem: {{ (.Files.Get "certificates/usercert.pem") | b64enc }}
  userkey.pem: {{ (.Files.Get "certificates/userkey.pem") | b64enc }}

---
apiVersion: v1
kind: Secret
metadata:
  name: rucio-ca-secret
type: Opaque
data:
  ca.pem: {{ (.Files.Get "certificates/ca.pem") | b64enc }}
  209843b3.0: {{ (.Files.Get "certificates/209843b3.0") | b64enc }}

---
# ===================================================================
#  Secret for Rucio OIDC idpsecrets.json
# ===================================================================
{{- if .Values.oidcCredentials.clientSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: rucio-oidc-secret
type: Opaque
stringData:
  # Rucio requires a JSON file for OIDC providers
  # FIX: We need BOTH the specific issuer key AND the 'default' key
  idpsecrets.json: |
    {
      "{{ .Values.oidcCredentials.adminIssuer }}": {
        "client_id": "{{ .Values.oidcCredentials.clientId }}",
        "client_secret": "{{ .Values.oidcCredentials.clientSecret }}",
        "issuer": "{{ .Values.oidcCredentials.oidcIssuer }}",
        "redirect_uris": [
          "{{ .Values.oidcCredentials.redirectUri }}"
        ],
        "scope": "openid profile offline_access storage.read:/ storage.create:/ storage.modify:/ wlcg wlcg.groups",
        "SCIM": {
          "client_id": "{{ .Values.oidcCredentials.clientId }}",
          "client_secret": "{{ .Values.oidcCredentials.clientSecret }}",
          "issuer": "{{ .Values.oidcCredentials.oidcIssuer }}",
          "redirect_uris": [
            "{{ .Values.oidcCredentials.redirectUri }}"
          ],
          "scope": "openid profile offline_access storage.read:/ storage.create:/ storage.modify:/ wlcg wlcg.groups"
        }
      },
      "default": {
        "client_id": "{{ .Values.oidcCredentials.clientId }}",
        "client_secret": "{{ .Values.oidcCredentials.clientSecret }}",
        "issuer": "{{ .Values.oidcCredentials.oidcIssuer }}",
        "redirect_uris": [
          "{{ .Values.oidcCredentials.redirectUri }}"
        ],
        "scope": "openid profile offline_access storage.read:/ storage.create:/ storage.modify:/ wlcg wlcg.groups",
        "SCIM": {
          "client_id": "{{ .Values.oidcCredentials.clientId }}",
          "client_secret": "{{ .Values.oidcCredentials.clientSecret }}",
          "issuer": "{{ .Values.oidcCredentials.oidcIssuer }}",
          "redirect_uris": [
            "{{ .Values.oidcCredentials.redirectUri }}"
          ],
          "scope": "openid profile offline_access storage.read:/ storage.create:/ storage.modify:/ wlcg wlcg.groups"
        }
      }
    }
{{- end }}