postgresql:
  auth:
    username: {{ .Values.postgres.user | quote }}
    password: {{ .Values.postgres.password | quote }}
    database: {{ .Values.postgres.db | quote }}

  primary:
    service:
      ports:
        postgresql: {{ .Values.postgres.port | default 5432 }}

    persistence:
      {{- if .Values.postgres.persistence }}
      enabled: {{ .Values.postgres.persistence.enabled | default false }}
      size: {{ .Values.postgres.persistence.size | default "5Gi" | quote }}
      {{- else }}
      enabled: false
      size: "5Gi"
      {{- end }}

  image:
    tag: {{ .Values.postgres.image | split ":" | last | quote }}